---
- name: group wheel
  group:
   name: wheel
   state: present

- name: allow passwordless
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: create user
  user:
    name: super
    password: "{{ pass }}"
    append: yes
    group: wheel
    state: present
    createhome: yes
    shell: /bin/bash

- name: add to root group
  shell: usermod -a -G root super
